/**
 * Comprehensive Economic Indexes
 * Real-time market data from Yahoo Finance
 */

export const ECONOMIC_INDEXES = [
  // Energy
  {
    id: 'oil',
    ticker: 'CL=F',
    name: 'Crude Oil WTI',
    shortName: 'Oil',
    category: 'ENERGY' as const,
    tier: 1,
    unit: '$/bbl',
    description: 'West Texas Intermediate crude oil futures',
    color: 'var(--warning)',
  },
  {
    id: 'brent',
    ticker: 'BZ=F',
    name: 'Brent Crude Oil',
    shortName: 'Brent',
    category: 'ENERGY' as const,
    tier: 1,
    unit: '$/bbl',
    description: 'Brent crude oil futures',
    color: 'var(--warning)',
  },
  {
    id: 'natgas',
    ticker: 'NG=F',
    name: 'Natural Gas',
    shortName: 'Nat Gas',
    category: 'ENERGY' as const,
    tier: 1,
    unit: '$/MMBtu',
    description: 'Natural gas futures',
    color: 'var(--info)',
  },
  {
    id: 'gasoline',
    ticker: 'RB=F',
    name: 'Gasoline',
    shortName: 'Gas',
    category: 'ENERGY' as const,
    tier: 2,
    unit: '$/gal',
    description: 'RBOB gasoline futures',
    color: 'var(--warning)',
  },
  
  // Safe Haven Assets (Precious Metals)
  {
    id: 'gold',
    ticker: 'GC=F',
    name: 'Gold',
    shortName: 'Gold',
    category: 'SAFE_HAVEN' as const,
    tier: 1,
    unit: '$/oz',
    description: 'Gold futures',
    color: 'var(--gold)',
  },
  {
    id: 'silver',
    ticker: 'SI=F',
    name: 'Silver',
    shortName: 'Silver',
    category: 'SAFE_HAVEN' as const,
    tier: 1,
    unit: '$/oz',
    description: 'Silver futures',
    color: 'var(--t3)',
  },
  {
    id: 'platinum',
    ticker: 'PL=F',
    name: 'Platinum',
    shortName: 'Platinum',
    category: 'SAFE_HAVEN' as const,
    tier: 2,
    unit: '$/oz',
    description: 'Platinum futures',
    color: 'var(--t2)',
  },
  {
    id: 'copper',
    ticker: 'HG=F',
    name: 'Copper',
    shortName: 'Copper',
    category: 'SAFE_HAVEN' as const,
    tier: 2,
    unit: '$/lb',
    description: 'Copper futures - industrial metal indicator',
    color: 'var(--warning)',
  },
  
  // Equities
  {
    id: 'sp500',
    ticker: '^GSPC',
    name: 'S&P 500',
    shortName: 'S&P 500',
    category: 'EQUITIES' as const,
    tier: 1,
    unit: 'pts',
    description: 'S&P 500 index',
    color: 'var(--blue)',
  },
  {
    id: 'nasdaq',
    ticker: '^IXIC',
    name: 'NASDAQ',
    shortName: 'NASDAQ',
    category: 'EQUITIES' as const,
    tier: 1,
    unit: 'pts',
    description: 'NASDAQ Composite index',
    color: 'var(--cyber)',
  },
  {
    id: 'dow',
    ticker: '^DJI',
    name: 'Dow Jones',
    shortName: 'Dow',
    category: 'EQUITIES' as const,
    tier: 1,
    unit: 'pts',
    description: 'Dow Jones Industrial Average',
    color: 'var(--blue)',
  },
  
  // Volatility
  {
    id: 'vix',
    ticker: '^VIX',
    name: 'VIX',
    shortName: 'VIX',
    category: 'VOLATILITY' as const,
    tier: 1,
    unit: 'pts',
    description: 'CBOE Volatility Index - fear gauge',
    color: 'var(--danger)',
  },
  
  // Currency
  {
    id: 'dxy',
    ticker: 'DX-Y.NYB',
    name: 'US Dollar Index',
    shortName: 'DXY',
    category: 'CURRENCY' as const,
    tier: 1,
    unit: 'pts',
    description: 'US Dollar Index',
    color: 'var(--success)',
  },
  {
    id: 'eurusd',
    ticker: 'EURUSD=X',
    name: 'EUR/USD',
    shortName: 'EUR/USD',
    category: 'CURRENCY' as const,
    tier: 2,
    unit: '',
    description: 'Euro to US Dollar exchange rate',
    color: 'var(--blue)',
  },
  {
    id: 'jpyusd',
    ticker: 'JPY=X',
    name: 'USD/JPY',
    shortName: 'USD/JPY',
    category: 'CURRENCY' as const,
    tier: 2,
    unit: '',
    description: 'US Dollar to Japanese Yen',
    color: 'var(--info)',
  },
  
  // Defense
  {
    id: 'lmt',
    ticker: 'LMT',
    name: 'Lockheed Martin',
    shortName: 'LMT',
    category: 'DEFENSE' as const,
    tier: 1,
    unit: '$',
    description: 'Lockheed Martin stock - defense contractor',
    color: 'var(--danger)',
  },
  {
    id: 'ba',
    ticker: 'BA',
    name: 'Boeing',
    shortName: 'Boeing',
    category: 'DEFENSE' as const,
    tier: 2,
    unit: '$',
    description: 'Boeing stock - aerospace & defense',
    color: 'var(--blue)',
  },
  {
    id: 'rtx',
    ticker: 'RTX',
    name: 'Raytheon',
    shortName: 'RTX',
    category: 'DEFENSE' as const,
    tier: 1,
    unit: '$',
    description: 'Raytheon Technologies - defense systems',
    color: 'var(--danger)',
  },
  {
    id: 'noc',
    ticker: 'NOC',
    name: 'Northrop Grumman',
    shortName: 'NOC',
    category: 'DEFENSE' as const,
    tier: 2,
    unit: '$',
    description: 'Northrop Grumman - defense contractor',
    color: 'var(--danger)',
  },
  
  // Shipping
  {
    id: 'zim',
    ticker: 'ZIM',
    name: 'ZIM Integrated',
    shortName: 'ZIM',
    category: 'SHIPPING' as const,
    tier: 2,
    unit: '$',
    description: 'ZIM shipping - container shipping rates',
    color: 'var(--info)',
  },
  {
    id: 'dac',
    ticker: 'DAC',
    name: 'Danaos Corp',
    shortName: 'DAC',
    category: 'SHIPPING' as const,
    tier: 2,
    unit: '$',
    description: 'Danaos - container shipping',
    color: 'var(--info)',
  },
];
